site_name: "AIchemy Hub Research Data"
site_url: "https://aichemy-hub.github.io/aichemy-research-data/"
repo_url: "https://github.com/aichemy-hub/aichemy-research-data"

theme:
  name: material
  logo: assets/logo.png
  features:
    - navigation.sections
    - navigation.instant
    - search.suggest
    - search.highlight

plugins:
  - search
  - macros

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Research Data: research-data.md
  - Licensing Guidelines: licensing-guidelines.md

extra_css:
  - stylesheets/tags.css
  - stylesheets/logo.css